import type { INodeProperties } from 'n8n-workflow';

export const searchOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['search'] } },
		options: [
			{
				name: 'Find',
				value: 'find',
				description:
					'Search files matching the given criteria (starts a search task on the NAS, waits for it and collects the results)',
				action: 'Find files',
			},
		],
		default: 'find',
	},
];

export const searchFields: INodeProperties[] = [
	{
		displayName: 'Folder Path',
		name: 'folderPath',
		type: 'string',
		required: true,
		default: '',
		placeholder: '/photo',
		description: 'Path of the folder to search in, starting with a shared folder',
		displayOptions: { show: { resource: ['search'], operation: ['find'] } },
	},
	{
		displayName: 'Pattern',
		name: 'pattern',
		type: 'string',
		default: '',
		placeholder: '*.jpg',
		description:
			'Case-insensitive glob pattern the file names must match. Without glob characters (* or ?) the pattern matches partially. Multiple patterns can be separated by spaces.',
		displayOptions: { show: { resource: ['search'], operation: ['find'] } },
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: { show: { resource: ['search'], operation: ['find'] } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		typeOptions: { minValue: 1 },
		description: 'Max number of results to return',
		displayOptions: { show: { resource: ['search'], operation: ['find'], returnAll: [false] } },
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: { resource: ['search'], operation: ['find'] } },
		options: [
			{
				displayName: 'Accessed After',
				name: 'atimeFrom',
				type: 'dateTime',
				default: '',
				description: 'Only files last accessed after this date',
			},
			{
				displayName: 'Accessed Before',
				name: 'atimeTo',
				type: 'dateTime',
				default: '',
				description: 'Only files last accessed before this date',
			},
			{
				displayName: 'Created After',
				name: 'crtimeFrom',
				type: 'dateTime',
				default: '',
				description: 'Only files created after this date',
			},
			{
				displayName: 'Created Before',
				name: 'crtimeTo',
				type: 'dateTime',
				default: '',
				description: 'Only files created before this date',
			},
			{
				displayName: 'Extension',
				name: 'extension',
				type: 'string',
				default: '',
				placeholder: 'jpg,png',
				description:
					'Only files whose extension matches this case-insensitive glob pattern. Multiple patterns can be separated by commas. Folders never match this filter.',
			},
			{
				displayName: 'File Type',
				name: 'fileType',
				type: 'options',
				options: [
					{ name: 'All', value: 'all' },
					{ name: 'Files Only', value: 'file' },
					{ name: 'Folders Only', value: 'dir' },
				],
				default: 'all',
			},
			{
				displayName: 'Group',
				name: 'group',
				type: 'string',
				default: '',
				description: 'Only files belonging to this group (case-insensitive)',
			},
			{
				displayName: 'Modified After',
				name: 'mtimeFrom',
				type: 'dateTime',
				default: '',
				description: 'Only files last modified after this date',
			},
			{
				displayName: 'Modified Before',
				name: 'mtimeTo',
				type: 'dateTime',
				default: '',
				description: 'Only files last modified before this date',
			},
			{
				displayName: 'Owner',
				name: 'owner',
				type: 'string',
				default: '',
				description: 'Only files owned by this user (case-insensitive)',
			},
			{
				displayName: 'Recursive',
				name: 'recursive',
				type: 'boolean',
				default: true,
				description: 'Whether to search within sub-folders',
			},
			{
				displayName: 'Size Larger Than',
				name: 'sizeFrom',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0 },
				description: 'Only files larger than this byte size',
			},
			{
				displayName: 'Size Smaller Than',
				name: 'sizeTo',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0 },
				description: 'Only files smaller than this byte size',
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add option',
		default: {},
		displayOptions: { show: { resource: ['search'], operation: ['find'] } },
		options: [
			{
				displayName: 'Additional Fields',
				name: 'additional',
				type: 'multiOptions',
				options: [
					{ name: 'Owner', value: 'owner' },
					{ name: 'Permissions', value: 'perm' },
					{ name: 'Real Path', value: 'real_path' },
					{ name: 'Size', value: 'size' },
					{ name: 'Time', value: 'time' },
					{ name: 'Type', value: 'type' },
				],
				default: [],
				description: 'Extra file information to include in the results',
			},
			{
				displayName: 'Max Wait Time',
				name: 'maxWaitTime',
				type: 'number',
				default: 60,
				typeOptions: { minValue: 1 },
				description: 'Maximum time in seconds to wait for the search to finish',
			},
			{
				displayName: 'Sort By',
				name: 'sortBy',
				type: 'options',
				options: [
					{ name: 'Access Time', value: 'atime' },
					{ name: 'Change Time', value: 'ctime' },
					{ name: 'Created Time', value: 'crtime' },
					{ name: 'Extension', value: 'type' },
					{ name: 'Group', value: 'group' },
					{ name: 'Modified Time', value: 'mtime' },
					{ name: 'Name', value: 'name' },
					{ name: 'Owner', value: 'user' },
					{ name: 'POSIX Permissions', value: 'posix' },
					{ name: 'Size', value: 'size' },
				],
				default: 'name',
			},
			{
				displayName: 'Sort Direction',
				name: 'sortDirection',
				type: 'options',
				options: [
					{ name: 'Ascending', value: 'asc' },
					{ name: 'Descending', value: 'desc' },
				],
				default: 'asc',
			},
		],
	},
];
